### ISSUE TITLE
How do I access the pod logs?

### ISSUE THREAD

**Issue by theallseingeye** [maclof/kubernetes-client#39]
Could you give an example of how to access the pod logs?

Thanks

**Comment by maclof** [comment]
@theallseingeye for example if you have a pod with the metadata name as "mcrouter-vfmtx" and a container with the name "mcrouter" you can find the last 100 log lines like this:

```php
$pod = $kubernetesClient->pods()->setFieldSelector([
	'metadata.name' => 'mcrouter-vfmtx',
])->find()->first();

$logs = $kubernetesClient->pods()->logs($pod, [
	'timestamps' => true,
	'tailLines'  => 100,
	'container'  => 'mcrouter',
]);
```

You could also use setLabelSelector() instead of setFieldSelector, or both if you wish to have really fine grained control over the search.
